import { type IEntitiesService } from '@kinotic/structures-api'
import { BaseTodoEntityService } from './generated/BaseTodoEntityService.js'

/**
 * Service for interacting with Todo entities
 * This class was generated by the structures cli
 */
export class TodoEntityService extends BaseTodoEntityService {

  constructor(entitiesService?: IEntitiesService) {
    super(false, entitiesService)
  }

}
