import { AutoGeneratedId, Entity, MultiTenancyType } from "@kinotic/structures-api"

@Entity(MultiTenancyType.SHARED)
export class Todo {
    @AutoGeneratedId
    id!: string
    title!: string
    description!: string
    completed!: boolean
}